version: '3.2'
services:
  http:
    image: nginx:1.15-alpine
    depends_on:
      - php
    ports:
     - "${NGINX_PORT}:80"
    volumes:
      - ./resources/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./public:/srv/public
  php:
    restart: always
    build:
      context: ./resources/docker/php
    working_dir: /srv
    volumes:
      - ./:/srv/:cached
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
